calculate_monthly_fee_job:
  cron: '0 0 1 * *'
  class: 'CreateMonthlyFeesJob'
  args:
    - null
  queue: default
  description: 'Calculate monthly fees for the previous month at the beginning of each month'
