name: "Build"

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: api
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop -P
      
      - name: Migrate Database
        env:
          RAILS_ENV: "test"
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec spec
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/sequra_pay_hub_test"
